on: [push] 

jobs:
  deploy_job:
    runs-on: ubuntu-latest  
    name: sftp
    steps:
      - name: Checkout    
        uses: actions/checkout@v2 

      - name: Deploy file
        uses: wlixcc/SFTP-Deploy-Action@v1.2.4
        with:
                username: ${{ secrets.user }}
                server: ${{ secrets.ip }}
                port: 22
                local_path: './*'
                remote_path: ${{ secrets.path }}
                sftp_only: true
                password: ${{ secrets.password }}
