on: push
name: 🚀 Deploy website on push
jobs:
  web-deploy:
    name: 🎉 Deploy
    runs-on: ubuntu-latest
    steps:
    - name: 🚚 Get latest code
      uses: actions/checkout@v2

    - name: 📂 Sync files
      uses: SamKirkland/FTP-Deploy-Action@4.3.1
      with:
        server: ${{ secrets.ip }}
        username: ${{ secrets.user }}
        password: ${{ secrets.password }}
        protocol: ftps
        server-dir: ${{ secrets.path }}
        port: 22 # todo replace with your web hosts ftps port
        security: strict
        timeout: 600000
        log-level: verbose
